pipeline {
    environment {
        repository = "sjs3326"
        DOCKERHUB_CREDENTIALS = credentials('dockerhub_token')
        dockerImage = ''
    }

    agent any

    stages {
        stage('Clone Repository') {
            steps {
                checkout scm
            }
        }
        stage('Build Project') {
            steps {
                dir("./backend/service-discovery") {
                    sh "chmod +x ./gradlew"
                    sh "./gradlew clean build"
                }
            }
        }
        stage('Build Discovery-Server Image'){
             steps{
                   script{
                        dockerImage = docker.build("\${env.repository}/test", "-f backend/service-discovery/Dockerfile ./backend/service-discovery")
                   }
              }
        }

        stage('DockerHub Login'){
            steps{
                script{
                    sh "echo \${DOCKERHUB_PASSWORD} | docker login -u \${DOCKERHUB_USER} --password-stdin"
                }
            }
        }

        stage('Clean Service Discovery Image'){
            steps{
                script{
                     sh "docker rmi \${env.repository}/test"
                }
            }
        }

        stage('Push Service Discovery Image'){
            steps{
                script{
                     sh "docker push \${env.repository}/test"
                }
            }
        }


    }
}
