# Use the official MongoDB image as the base image
FROM mongo:latest

# Set environment variables for MongoDB
ENV MONGO_INITDB_ROOT_USERNAME=root \
    MONGO_INITDB_ROOT_PASSWORD=root \
    PATH=$PATH:/path/to/mongodb/bin
# Expose the default MongoDB port
EXPOSE 27017
